src/main/java/com/backend/allreva/artist/command/domain/Artist.java
src/main/java/com/backend/allreva/auth/oauth2/application/CustomOAuth2UserService.java
src/main/java/com/backend/allreva/auth/oauth2/application/dto/OAuth2UserInfo.java
src/main/java/com/backend/allreva/common/model/Image.java
src/main/java/com/backend/allreva/concert/command/application/dto/KopisConcertResponse.java
src/main/java/com/backend/allreva/concert/command/domain/Concert.java
src/main/java/com/backend/allreva/diary/command/domain/ConcertDiary.java
src/main/java/com/backend/allreva/member/command/application/MemberRepository.java
src/main/java/com/backend/allreva/member/command/domain/Member.java
src/main/java/com/backend/allreva/member/command/domain/MemberArtist.java
src/main/java/com/backend/allreva/member/command/domain/value/LoginProvider.java
src/main/java/com/backend/allreva/member/command/domain/value/MemberInfo.java
src/main/java/com/backend/allreva/member/command/domain/value/MemberRole.java
src/main/java/com/backend/allreva/rent/command/domain/RentForm.java
src/main/java/com/backend/allreva/rent/command/domain/RentJoin.java
src/main/java/com/backend/allreva/rent/command/domain/value/AdditionalInfo.java
src/main/java/com/backend/allreva/rent/command/domain/value/BoardingType.java
src/main/java/com/backend/allreva/rent/command/domain/value/Bus.java
src/main/java/com/backend/allreva/rent/command/domain/value/BusSize.java
src/main/java/com/backend/allreva/rent/command/domain/value/BusType.java
src/main/java/com/backend/allreva/rent/command/domain/value/Depositor.java
src/main/java/com/backend/allreva/rent/command/domain/value/DetailInfo.java
src/main/java/com/backend/allreva/rent/command/domain/value/OperationInfo.java
src/main/java/com/backend/allreva/rent/command/domain/value/Price.java
src/main/java/com/backend/allreva/rent/command/domain/value/RefundType.java
src/main/java/com/backend/allreva/rent/command/domain/value/Region.java

- closed #23 
Artist, RentForm, Diary Entity를 생성하였습니다.
erd와 다른 부분이 있다면 말씀 주세용

[ARV-24] Artist, RentForm, Diary Entity 생성

---

src/main/java/com/backend/allreva/auth/exception/CustomAccessDeniedHandler.java
src/main/java/com/backend/allreva/auth/util/JwtTestTokenInitializer.java
src/main/java/com/backend/allreva/common/config/SwaggerConfig.java
src/main/java/com/backend/allreva/common/runner/MemberDummyDataInitializer.java

- closed #33 
Swagger에 권한 별 Token 적용할 수 있는 Authorize 칸을 추가했습니다.

[ARV-36] JWT Swagger 설정

---

src/main/java/com/backend/allreva/common/config/SecurityConfig.java

- closed #41 
CORS 설정 임시로 모든 경로에 대해 disable 하였습니다.

[ARV-51] CORS 설정

---

.gitignore
src/main/java/com/backend/allreva/concert/command/domain/Concert.java
src/main/java/com/backend/allreva/concert/command/domain/value/SortDirection.java
src/main/java/com/backend/allreva/concert/query/application/ConcertQueryService.java
src/main/java/com/backend/allreva/concert/ui/ConcertController.java
src/main/java/com/backend/allreva/search/infra/CustomConcertSearchRepo.java
src/main/java/com/backend/allreva/search/infra/CustomConcertSearchRepoImpl.java
src/main/java/com/backend/allreva/search/query/application/ConcertSearchService.java
src/main/java/com/backend/allreva/search/query/application/dto/ConcertSearchListResponse.java
src/main/java/com/backend/allreva/search/query/domain/value/SearchField.java
src/main/java/com/backend/allreva/search/query/domain/value/SortDirection.java
src/main/java/com/backend/allreva/search/ui/SearchController.java
src/test/java/com/backend/allreva/concert/query/application/ConcertQueryServiceTest.java
src/test/java/com/backend/allreva/search/query/application/ConcertSearchServiceTest.java

- closed #58 
콘서트 검색 더보기 API 구현

[ARV-69] 콘서트 검색 더보기 API 구현list

---

src/main/java/com/backend/allreva/common/config/WebMvcConfig.java

- closed #84 
```java
@Configuration
public class WebMvcConfig implements WebMvcConfigurer {
@Override
public void addCorsMappings(CorsRegistry registry) {
registry.addMapping("/**")
.allowedOriginPatterns("*")
.allowCredentials(true)
.allowedMethods("GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS")
.allowedHeaders("*")
.maxAge(3600);
}
}
```

[ARV-106] CORS 설정

---

src/main/java/com/backend/allreva/common/config/SecurityConfig.java

- closed #86 
Concert main api 보안 전체허용

[ARV-107] Concert main api 보안 전체허용

---

.github/workflows/CICD.yml
build.gradle
src/main/java/com/backend/allreva/common/config/KafkaConfig.java
src/main/java/com/backend/allreva/concert/command/domain/Concert.java
src/main/java/com/backend/allreva/concert/infra/ConcertRepositoryImpl.java
src/main/java/com/backend/allreva/concert/query/application/dto/ConcertThumbnail.java
src/main/java/com/backend/allreva/search/exception/EventConsumingException.java
src/main/java/com/backend/allreva/search/exception/EventPublishingException.java
src/main/java/com/backend/allreva/search/exception/SearchErrorCode.java
src/main/java/com/backend/allreva/search/infra/ConcertLikeConsumer.java
src/main/java/com/backend/allreva/search/infra/ConcertLikeProducer.java
src/main/java/com/backend/allreva/search/infra/ConcertSearchRepository.java
src/main/java/com/backend/allreva/search/query/domain/ConcertDocument.java
src/main/java/com/backend/allreva/search/query/domain/ConcertLikeEvent.java
src/main/resources/elasticsearch/mappings/es-mapping.json
src/main/resources/elasticsearch/mappings/es-settings.json
src/test/java/com/backend/allreva/concert/ConcertQueryTest.java
src/test/java/com/backend/allreva/search/infra/ConcertRepositoryTest.java
src/test/java/com/backend/allreva/search/infra/EventSyncTest.java

- closed #68 
카프카를 이용해 조회수 증가 스케쥴러 동작시 이벤트를 날려 일라스틱 서치에 있는 콘서트 조회수와 sync를 했습니다.
@kwanse 이벤트 위주로 봐주세요

[ARV-93] mysql elasticsearch 조회수 sync

---

src/main/java/com/backend/allreva/member/ui/MemberController.java

<br>
- closed #94
스웨거에서 예제응답이 보이지 않아서 @APIResponse 제거하고 Response로 응답통일하였습니다. 별 수정 없어서 바로 머지하셔도됩니다~~

[ARV-118] MemberController 수정

---

src/main/java/com/backend/allreva/rent/infra/CustomRentDocumentRepo.java
src/main/java/com/backend/allreva/rent/infra/CustomRentDocumentRepoImpl.java
src/main/java/com/backend/allreva/rent/query/application/RentDocumentService.java
src/main/java/com/backend/allreva/rent/query/application/domain/RentDocument.java
src/main/java/com/backend/allreva/rent/query/application/domain/RentDocumentRepository.java
src/main/java/com/backend/allreva/rent/query/application/dto/RentSearchListResponse.java
src/main/java/com/backend/allreva/rent/query/application/dto/RentThumbnail.java
src/main/java/com/backend/allreva/rent/ui/RentSearchController.java
src/main/java/com/backend/allreva/survey/query/application/dto/SurveyThumbnail.java
src/main/java/com/backend/allreva/survey/ui/SurveySearchController.java
src/main/resources/elasticsearch/mappings/rent-mapping.json
src/test/java/com/backend/allreva/rent/query/application/RentDocumentServiceTest.java

- closed #98 
차대절 검색 api 구현
차대절 검색 api 구현 무한열차
검색 구현 위주로 봐주세용!!

[ARV-119] 차대절 검색 api 구현

---

src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java

- closed #109 
OAuth2 로그인 성공 시 redirect URL을 `localhost:3000`으로 수정하였습니다

[ARV-132] OAuth2 리다이렉트 급하게 수정

---

src/main/java/com/backend/allreva/concert/command/domain/ConcertRepository.java
src/main/java/com/backend/allreva/concert/infra/repository/ConcertDslRepository.java
src/main/java/com/backend/allreva/concert/infra/repository/ConcertDslRepositoryImpl.java
src/main/java/com/backend/allreva/concert/infra/repository/ConcertRepositoryImpl.java
src/main/java/com/backend/allreva/concert/infra/repository/CustomConcertSearchRepoImpl.java
src/main/java/com/backend/allreva/concert/query/application/ConcertQueryService.java
src/main/java/com/backend/allreva/concert/ui/ConcertController.java
src/main/java/com/backend/allreva/rent/infra/CustomRentDocumentRepoImpl.java
src/main/java/com/backend/allreva/rent/infra/RentQueryRepositoryImpl.java
src/main/java/com/backend/allreva/rent/query/application/RentQueryRepository.java
src/main/java/com/backend/allreva/rent/query/application/RentQueryService.java
src/main/java/com/backend/allreva/rent/ui/RentViewController.java
src/main/java/com/backend/allreva/survey/infra/CustomSurveyDocumentRepoImpl.java
src/main/java/com/backend/allreva/survey/infra/SurveyQueryRepositoryImpl.java
src/main/java/com/backend/allreva/survey/query/application/SurveyQueryService.java
src/main/java/com/backend/allreva/survey/query/application/domain/SurveyQueryRepository.java
src/main/java/com/backend/allreva/survey/ui/SurveyController.java

- closed #105 
콘서트 메인 API 구현
차대절 메인 API 구현
수요 조사 메인 API 구현
Repository 위주로 봐 주세요

[ARV-128] 메인 API 구현

---

src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/backend/allreva/auth/util/CookieUtil.java

- closed #112 
임시로 redirect한 url에 access token을 param으로 넣었습니다.
HTTPS가 적용되는 대로 Secure Cookie에 넣을 생각입니다.

[ARV-133] Cookie가 인식되지 않은 문제 수정

---

src/main/java/com/backend/allreva/common/config/SwaggerConfig.java

<br>
- closed #116
요청 url 2개로 분리
allreva.shop , localhost:8080

[ARV-136] Https 설정에 따른 SwaggerConfig 변경

---

src/main/java/com/backend/allreva/auth/oauth2/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/backend/allreva/auth/util/CookieUtil.java

- closed #118 
토큰 Secure Cookie를 적용했습니다.

[ARV-137] 토큰 Secure Cookie 적용

---

src/main/java/com/backend/allreva/auth/util/CookieUtil.java

- closed #121 
Cookie domain을 localhost로 수정했습니다

[ARV-138] 쿠키 Cross Site 정책 적용

---

src/main/java/com/backend/allreva/hall/infra/dto/KopisHallResponse.java

<br>
- closed #137 
아주아주 간단한 중복제거 로직 추가
안해봤음
저 로직 하나밖에 없음

[ARV-163] 시설명과 공연장명 중복 제거

---

src/main/java/com/backend/allreva/common/config/SecurityEndpointPaths.java

<br>
- closed #139 
serveys -> surveys 로 오타 수정
artists/search 인증 제거

[ARV-164] fix: 아티스트 검색에 인증 제거 및 오타 수정

---

src/main/java/com/backend/allreva/artist/query/application/response/Image.java

- closed #141 
아티스트 검색시 이미지 추가

[ARV-165] 아티스트 검색 API 아티스트 이미지 URL 없음 해결

---

src/main/java/com/backend/allreva/concert/query/application/ConcertSearchService.java
src/main/java/com/backend/allreva/keyword/command/PopularKeywordCommandService.java

인기 검색어 최초 등록 시 NullPointerException이 뜨던 오류를 해결하였습니다.

[ARV-144] 검색어 증가 구현 수정

---

src/main/java/com/backend/allreva/auth/security/JwtAuthenticationFilter.java

- closed #149 
- 와일드카드 적용을 위해 equals() 대신 AntPathMatcher 사용

[ARV-172] 토큰 재발급 이슈 수정

---

src/main/java/com/backend/allreva/common/config/SecurityConfig.java
src/main/java/com/backend/allreva/common/config/SecurityEndpointPaths.java

- closed #151 
- ANONYMOUS 권한을 먼저 설정
- ANONYMOUS로 허용할 URL은 구체적으로 작성, USER 이상 권한은 와일드카드 대체
- 이전 코드에서 Handler가 중복으로 등록되어 403 Handler가 적용되지 않는 문제 발생
- exceptionHandling() 한 번의 호출로 둘 다 등록하도록 수정

[ARV-173] 권한 허용 URL 수정

---

src/main/java/com/backend/allreva/concert/infra/elasticsearch/ConcertSearchRepository.java
src/main/java/com/backend/allreva/concert/infra/elasticsearch/CustomConcertSearchRepo.java
src/main/java/com/backend/allreva/concert/infra/elasticsearch/CustomConcertSearchRepoImpl.java
src/main/java/com/backend/allreva/concert/query/application/ConcertSearchService.java
src/main/java/com/backend/allreva/concert/ui/ConcertSearchController.java
src/main/java/com/backend/allreva/rent/infra/elasticsearch/CustomRentDocumentRepoImpl.java
src/main/java/com/backend/allreva/rent/infra/elasticsearch/RentDocumentRepository.java
src/main/java/com/backend/allreva/survey/infra/elasticsearch/CustomSurveyDocumentRepoImpl.java
src/main/java/com/backend/allreva/survey/infra/elasticsearch/SurveyDocumentRepository.java
src/test/java/com/backend/allreva/keyword/integration/ConcertSearchServiceTest.java
src/test/java/com/backend/allreva/keyword/repository/ConcertRepositoryTest.java

- closed #157 
전체기간 공연 검색 API 추가

Arv 182 feat/all period concert search

---

src/main/java/com/backend/allreva/concert/query/application/response/ConcertThumbnail.java

<br>
- closed #159 
ex) 콘서트 검색 Response episodes 추가

[ARV-183] fix 콘서트 검색 Response episodes 추가

---

src/main/java/com/backend/allreva/rent/ui/RentSearchControllerSwagger.java
src/main/java/com/backend/allreva/survey/infra/elasticsearch/CustomSurveyDocumentRepoImpl.java

<br>
- closed #161 
rent 검색 무한스크롤 오류 해결 (Swagger interface 문제)

[ARV-184] fix rent 검색 무한스크롤 오류 해결

---

src/main/java/com/backend/allreva/common/config/CorsConfig.java
src/main/java/com/backend/allreva/concert/infra/rdb/ConcertRepositoryImpl.java

[ARV-185] refactor: cache 리팩토링

---

src/main/java/com/backend/allreva/concert/query/application/response/ConcertDetailResponse.java
src/main/java/com/backend/allreva/rent/infra/rdb/RentDslRepositoryImpl.java
src/main/java/com/backend/allreva/rent/infra/rdb/RentRepositoryImpl.java
src/main/java/com/backend/allreva/rent/query/application/RentQueryService.java
src/main/java/com/backend/allreva/rent/query/application/response/RentJoinCountResponse.java

[ARV-186] fix: rent 버그 수정

---

src/main/java/com/backend/allreva/concert/query/application/response/ConcertDetailResponse.java
src/main/java/com/backend/allreva/diary/infra/DiaryDslRepositoryImpl.java
src/main/java/com/backend/allreva/diary/query/response/DiarySummaryResponse.java
src/main/java/com/backend/allreva/rent/infra/rdb/RentDslRepositoryImpl.java
src/main/java/com/backend/allreva/rent/infra/rdb/RentRepositoryImpl.java
src/main/java/com/backend/allreva/rent/query/application/RentQueryService.java
src/main/java/com/backend/allreva/rent/query/application/response/RentJoinCountResponse.java

[ARV-186] diary 수정

---

src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
src/main/java/com/backend/allreva/diary/command/domain/ConcertDiary.java
src/test/java/com/backend/allreva/diary/domain/DiaryDomainTest.java

[ARV-188] fix: diary 이미지 수정 버그 수정

---

build.gradle
src/main/java/com/backend/allreva/chat/domain/ChatMessage.java
src/main/java/com/backend/allreva/chat/ui/AddGroupChatRoomRequest.java
src/main/java/com/backend/allreva/chat/ui/ChatController.java
src/main/java/com/backend/allreva/chat/ui/ChatRoomMembersResponse.java
src/main/java/com/backend/allreva/chat/ui/ChatRoomSummaryResponse.java
src/main/java/com/backend/allreva/chat/ui/ChatRoomSwagger.java
src/main/java/com/backend/allreva/chat/ui/ExampleResponse.java
src/main/java/com/backend/allreva/common/config/WebSocketConfig.java

<br>
- closed #
성공!
그냥 스웨거 등록용임!

[ARV-192] 채팅 스웨거 등록

---

src/main/java/com/backend/allreva/concert/command/domain/Concert.java
src/main/java/com/backend/allreva/concert/infra/dto/KopisConcertResponse.java
src/main/java/com/backend/allreva/concert/infra/rdb/ConcertDslRepositoryImpl.java
src/main/java/com/backend/allreva/concert/query/application/response/ConcertDetailResponse.java
src/main/java/com/backend/allreva/diary/command/domain/ConcertDiary.java
src/main/java/com/backend/allreva/diary/infra/DiaryDslRepositoryImpl.java
src/main/java/com/backend/allreva/diary/query/response/DiaryDetailResponse.java
src/test/java/com/backend/allreva/concert/fixture/ConcertFixture.java
src/test/java/com/backend/allreva/concert/integration/ConcertQueryTest.java
src/test/java/com/backend/allreva/support/IntegrationTestSupport.java

<br>
- closed #175 
순서 문제로 Set -> List 리팩토링 진행
성공
Concert, ConcertDiary 도메인

[ARV-197] refactor: Set -> List 리팩토링

---

src/main/java/com/backend/allreva/common/application/FileController.java
src/main/java/com/backend/allreva/common/application/FileService.java
src/main/java/com/backend/allreva/common/application/dto/GetPresignedUrlRequest.java
src/main/java/com/backend/allreva/common/config/S3Config.java
src/main/java/com/backend/allreva/seat_review/command/application/SeatReviewFacade.java
src/main/java/com/backend/allreva/seat_review/command/application/SeatReviewImageService.java
src/main/java/com/backend/allreva/seat_review/command/application/dto/ReviewCreateRequest.java
src/main/java/com/backend/allreva/seat_review/command/application/dto/ReviewUpdateRequest.java
src/main/java/com/backend/allreva/seat_review/exception/SeatReviewErrorCode.java
src/main/java/com/backend/allreva/seat_review/exception/SeatReviewImageDeleteException.java
src/main/java/com/backend/allreva/seat_review/infra/SeatReviewRepositoryCustomImpl.java
src/main/java/com/backend/allreva/seat_review/query/application/dto/SeatReviewResponse.java
src/main/java/com/backend/allreva/seat_review/ui/SeatReviewController.java
src/main/java/com/backend/allreva/seat_review/ui/SeatReviewControllerSwagger.java
src/main/java/com/backend/allreva/seat_review/ui/SeatReviewSearchCondition.java
src/main/java/com/backend/allreva/seat_review/ui/SortType.java

<br>
- closed #188 
리뷰 조회 최신순 오래된순 으로 변경
닉네임,프로필사진 reponse 추가
해당 리뷰가 본인이 쓴건지 아닌지 여부 확인할 수 있는 필드추가
이미지 presignedURL 방식으로 변경

[ARV-213] 공연장 도메인 refactoring

---

src/main/java/com/backend/allreva/common/dummy/DummyController.java
src/main/java/com/backend/allreva/seat_review/command/application/SeatReviewService.java
src/main/java/com/backend/allreva/seat_review/command/application/dto/ReviewCreateRequest.java
src/main/java/com/backend/allreva/seat_review/command/application/dto/ReviewUpdateRequest.java
src/main/java/com/backend/allreva/seat_review/command/domain/SeatReview.java
src/main/java/com/backend/allreva/seat_review/infra/SeatReviewRepositoryCustomImpl.java
src/main/java/com/backend/allreva/seat_review/query/application/dto/SeatReviewResponse.java

[ARV-216] 공연장 리뷰 조회 수정

---

.github/workflows/CICD.yml

- closed #195 
```yaml
- name: Create application.yml
run: |
mkdir -p src/main/resources
mkdir -o src/main/resources/firebase => mkdir -p src/main/resources/firebase
```
`-o`를 `-p`로 수정했습니다

[ARV-217] CD script 오타 수정

---

.github/workflows/CICD.yml

<br>
- closed #191 
CI 스크립트 수정

[ARV-215] CI 스크립트 수정

---

src/main/java/com/backend/allreva/common/event/NotificationEvent.java
src/main/java/com/backend/allreva/common/event/NotificationMessage.java
src/main/java/com/backend/allreva/notification/command/NotificationService.java
src/main/java/com/backend/allreva/rent/command/application/RentCommandFacade.java

- closed #204 
매개변수 순서가 반대로 되어있던 것을 수정했습니다.
rent 생성 시 생성자 본인에게 알림을 보내는 로직을 추가했습니다.
테스트 성공 후 나머지 일괄 추가 예정
성공했습니다!

[ARV-222] 알림 로직 적용

---

src/main/java/com/backend/allreva/common/event/NotificationMessage.java
src/main/java/com/backend/allreva/firebase/util/FcmTokenUtils.java
src/main/java/com/backend/allreva/notification/command/NotificationService.java
src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java

- closed #204 
수요 조사 개설 시 알림 기능 추가

[ARV-222] 알림 로직 추가 적용

---

.github/workflows/create-jira-issue.yml
src/main/java/com/backend/allreva/chatting/chat/group/command/application/GroupChatCommandService.java
src/main/java/com/backend/allreva/chatting/chat/group/command/application/request/UpdateGroupChatRequest.java
src/main/java/com/backend/allreva/chatting/chat/group/ui/GroupChatController.java
src/main/java/com/backend/allreva/common/dummy/DummyController.java
src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
src/main/java/com/backend/allreva/diary/command/application/request/AddDiaryRequest.java
src/main/java/com/backend/allreva/diary/command/application/request/UpdateDiaryRequest.java
src/main/java/com/backend/allreva/diary/ui/DiaryController.java
src/test/java/com/backend/allreva/diary/integration/DiaryCommandTest.java
src/test/java/com/backend/allreva/diary/integration/DiaryQueryTest.java

[ARV-225] 이미지 body 수정

---

.github/workflows/create-jira-issue.yml
src/main/java/com/backend/allreva/chatting/chat/group/command/application/GroupChatCommandService.java
src/main/java/com/backend/allreva/chatting/chat/group/command/application/request/UpdateGroupChatRequest.java
src/main/java/com/backend/allreva/chatting/chat/group/ui/GroupChatController.java
src/main/java/com/backend/allreva/chatting/chat/integration/infra/ChatParticipantCustomRepositoryImpl.java
src/main/java/com/backend/allreva/chatting/chat/integration/infra/ParticipantEventHandler.java
src/main/java/com/backend/allreva/chatting/notification/ChatNotificationController.java
src/main/java/com/backend/allreva/common/dummy/DummyController.java
src/main/java/com/backend/allreva/common/event/NotificationMessage.java
src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
src/main/java/com/backend/allreva/diary/command/application/request/AddDiaryRequest.java
src/main/java/com/backend/allreva/diary/command/application/request/UpdateDiaryRequest.java
src/main/java/com/backend/allreva/diary/ui/DiaryController.java
src/main/java/com/backend/allreva/firebase/util/FcmTokenUtils.java
src/main/java/com/backend/allreva/notification/command/NotificationService.java
src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java
src/test/java/com/backend/allreva/diary/integration/DiaryCommandTest.java
src/test/java/com/backend/allreva/diary/integration/DiaryQueryTest.java

[ARV-224] fix: mongoTemplate 관련 에러 수정

---

.github/workflows/create-jira-issue.yml
src/main/java/com/backend/allreva/chatting/chat/group/command/application/GroupChatCommandService.java
src/main/java/com/backend/allreva/chatting/chat/group/command/application/request/UpdateGroupChatRequest.java
src/main/java/com/backend/allreva/chatting/chat/group/ui/GroupChatController.java
src/main/java/com/backend/allreva/chatting/chat/integration/infra/ChatParticipantCustomRepositoryImpl.java
src/main/java/com/backend/allreva/chatting/chat/integration/infra/ParticipantEventHandler.java
src/main/java/com/backend/allreva/chatting/notification/ChatNotificationController.java
src/main/java/com/backend/allreva/common/config/FcmInitializer.java
src/main/java/com/backend/allreva/common/config/WebSocketConfig.java
src/main/java/com/backend/allreva/common/dummy/DummyController.java
src/main/java/com/backend/allreva/common/event/NotificationMessage.java
src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
src/main/java/com/backend/allreva/diary/command/application/request/AddDiaryRequest.java
src/main/java/com/backend/allreva/diary/command/application/request/UpdateDiaryRequest.java
src/main/java/com/backend/allreva/diary/ui/DiaryController.java
src/main/java/com/backend/allreva/firebase/util/FcmTokenUtils.java
src/main/java/com/backend/allreva/notification/command/NotificationService.java
src/main/java/com/backend/allreva/notification/infra/NotificationJdbcRepository.java
src/main/java/com/backend/allreva/survey/command/application/SurveyCommandService.java
src/test/java/com/backend/allreva/diary/integration/DiaryCommandTest.java
src/test/java/com/backend/allreva/diary/integration/DiaryQueryTest.java

<br>
- closed #
STOMP CONNECT 시 헤더 값을 인증에 사용하도록 수정
성공

[ARV-224] 채팅 인증 수정

---

src/main/java/com/backend/allreva/chatting/notification/ChatNotificationController.java

<br>
- closed #
SSE HttpResponse 에서 CORS 설정하던 코드 삭제
성공

SSE disconnect 해결

---

src/main/java/com/backend/allreva/chatting/chat/integration/infra/ParticipantEventHandler.java

[hotfix] 채팅 목록 관련 에러 해결
